server:
  port: 8081

spring:
  application:
    name: hotel-service
  r2dbc:
    url: r2dbc:h2:mem:///hoteldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      management:
        context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,build,git
  endpoint:
    health:
      show-details: always
